### ISSUE TITLE
make for android

### ISSUE THREAD

**Issue by lattice0** [biraj21/texterm#4]
this looks like the perfect editor to put on my android phone which has none. Nano needs some system libs. Could you add support for Android compilation?

This is how I compile other C projects for Android

```
set -ex
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export TOOLCHAIN=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=aarch64-linux-android
#minSdkVersion.
export API=28
export AR=$TOOLCHAIN/bin/llvm-ar
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export AS=$CC
export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
export LD=$TOOLCHAIN/bin/ld
export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
export STRIP=$TOOLCHAIN/bin/llvm-strip
(cd kex && autoreconf && LDFLAGS=-static ./configure --host $TARGET && make)
# needed because of https://github.com/termux/termux-packages/issues/8273
../align_fix.py ${SCRIPT_DIR}/kex/build/sbin/kexec
```

**Comment by biraj21** [comment]
Sorry for the late reply.

Idk how to do that. And also I am busy in understanding Deep Learning so am not working on this right now.

**Comment by biraj21** [comment]
Hello @lattice0. If you want to use Texterm on Android, then
- Install [Termux](https://github.com/termux/termux-app).
- Install git, clang and make on Termux.
- Clone this repo.
- Build with `make`.
